server:
  port: 8080

spring:
  application:
    name: ai-assistant

  datasource:
    url: jdbc:postgresql://localhost:5433/ai_assistant
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral
          temperature: 0.2

    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 1536

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans